### ISSUE TITLE
Feature: new HandlerLibrary::Enum

### ISSUE THREAD

**Issue by targzeta** [tobyink/p5-sub-handlesvia#10]
Hi,
it would be nice to have an handler that traits Enum type. 

I have see the MooX::Enumaration library, but it doesn't seem to work together MooX::late. Indeed, if I use MooX::late before MooX::Enumeration:
```perl
use Moo;
use MooX::late;
use MooX::Enumeration;

has string => (is => 'ro', isa => 'Str');
has status => (
    is      => "rw",
    enum    => [qw/pass fail/],
    handles => 1,
);
```
`Invalid isa 'Str' for Test->string is not a coderef or code-convertible object at /usr/local/share/perl5/MooX/Enumeration.pm line 53.`

Using MooX::Enumeration before MooX::late:
```perl
use Moo;
use MooX::Enumeration;
use MooX::late;

has string => (is => 'ro', isa => 'Str');
has status => (
    is      => "rw",
    enum    => [qw/pass fail/],
    handles => 1,
);
```
`"1" is not a module name! at /usr/local/share/perl5/Sub/HandlesVia/Toolkit/Moo.pm line 50.`

The desiderable configuration should be:
```perl
use Moo;
use MooX::late;

has status => (
  is => 'rw',
  isa => 'Enum [qw(pass fail)]',
  handles_via => 'Enum',
  handles => (
    isPass => 'is_pass',
    isFail => 'is_fail',
  )
);
```
Is it possible? What do you think about?

Thank you in advance,
Emanuele

**Comment by tobyink** [comment]
This already should work (though I haven't tested it):

```perl
has status => (
  is => 'rw',
  isa => 'Enum["pass","fail"]',
  handles_via => 'String',
  handles => {
    isPass  => [ eq  => 'pass' ],
    isFail  => [ eq  => 'fail' ],
    setPass => [ set => 'pass' ],
    setFail => [ set => 'fail' ],
  },
);
```

Some kind of shortcut would be nice though.

**Comment by tobyink** [comment]
```perl
use strict;
use warnings;
use Test::More;

package Local::Example {
	use Moo;
	use MooX::late;
	has status => (
		is => 'ro',
		isa => 'Enum["pass","fail"]',
		handles_via => 'String',
		handles => {
			isPass  => [ eq  => 'pass' ],
			isFail  => [ eq  => 'fail' ],
			setPass => [ set => 'pass' ],
			setFail => [ set => 'fail' ],
		},
	);
}

my $obj = Local::Example->new;

$obj->setPass;
ok( $obj->isPass );
ok( not $obj->isFail);
is( $obj->status, 'pass' );

$obj->setFail;
ok( not $obj->isPass );
ok( $obj->isFail);
is( $obj->status, 'fail' );

done_testing;
```

**Comment by targzeta** [comment]
Yes, it works fine! Thank you very much, Toby! It's a very good workaround for my problem. However, If you were to write an Enum handler library, I'll be glad to use it!

Emanuele

**Comment by targzeta** [comment]
Toby,
with many values is very tedious to write every 'set' and 'is' method in this way! Furthermore, I think these methods aren't chainedable, right?

Best regards,
Emanuele

**Comment by targzeta** [comment]
> > with many values is very tedious to write every 'set' and 'is' method in this way!
> 
> I'm working on a way to improve that.
> 
Ok, thank you very much!


> > Furthermore, I think these methods aren't chainedable, right?
> 
> Sub::HandlesVia allows any method to be made chainable using `...`:
> 
> ```perl
> has status => (
>   is => 'rw',
>   isa => 'Enum["pass","fail"]',
>   handles_via => 'String',
>   handles => {
>     isPass  => [ eq  => 'pass' ],
>     isFail  => [ eq  => 'fail' ],
>     setPass => [ 'set...' => 'pass' ],
>     setFail => [ 'set...' => 'fail' ],
>   },
> );
> ```
Ok!

Thank you again,
Emanuele

**Comment by targzeta** [comment]
Yes, it works with MooX::late too!

I think you should be add a link within:
- https://metacpan.org/pod/Sub::HandlesVia#SEE-ALSO
- https://metacpan.org/dist/Sub-HandlesVia/view/lib/Sub/HandlesVia/HandlerLibrary/String.pod#Using-eq-for-Enum

Thank you very much for your work, Toby!!!
Emanuele
