### ISSUE TITLE
tests broken by Type::Tiny 2.000000

### ISSUE THREAD

**Issue by SysPete** [tobyink/p5-sub-handlesvia#2]
Can't locate Devel/TypeTiny/Perl56Compat.pm in @INC `<snip>`

grep -r Devel::TypeTiny::Perl .
./t/00begin.t:  require Devel::TypeTiny::Perl56Compat;

**Comment by tobyink** [comment]
Thanks. Should be fixed in 0.037.

**Comment by SysPete** [comment]
@tobyink many thanks!
