### ISSUE TITLE
Weird interaction between Beam::Wire and Moose / Mouse

### ISSUE THREAD

**Issue by bbrtj** [tobyink/p5-sub-handlesvia#5]
This example fails to compile:
```
use Beam::Wire;

package ThisFailsRole {
	use Moose::Role;
	use Sub::HandlesVia;

	has 'test' => (
		is => 'rw',
		default => sub { [] },
		handles_via => 'Array',
		handles => {
			'add_test' => 'push',
		}
	);
}
```

The error message is weird:
```
Use of uninitialized value in string eq at /home/devenv/.carmel/5.36.0-amd64-freebsd/builds/Sub-HandlesVia-0.039/blib/lib/Sub/HandlesVia/Toolkit/Moo.pm line 201.
Use of uninitialized value in string eq at /home/devenv/.carmel/5.36.0-amd64-freebsd/builds/Sub-HandlesVia-0.039/blib/lib/Sub/HandlesVia/Toolkit/Moo.pm line 204.
Use of uninitialized value in string eq at /home/devenv/.carmel/5.36.0-amd64-freebsd/builds/Sub-HandlesVia-0.039/blib/lib/Sub/HandlesVia/Toolkit/Moo.pm line 208.
Can't call method "is_Coderef" on unblessed reference at /home/devenv/.carmel/5.36.0-amd64-freebsd/builds/Sub-HandlesVia-0.039/blib/lib/Sub/HandlesVia/Toolkit/Moo.pm line 240.
```

It will run without problems when (either of those):
- there's no Beam::Wire import prior to Sub::HandlesVia import
- the role is Moo::Role (not Moose or Mouse)

This is probably at least partly connected to #4, as Beam::Wire imports Moo.

I don't know what part of Beam::Wire causes that error. I tried copying import list of Beam::Wire and replacing one import in my file with several, but that did not trigger this issue, so it seems there's something else in this module that may be problematic.

**Comment by tobyink** [comment]
Fixed by #4.

I'll release a new version to CPAN later today.
