### ISSUE TITLE
Moose: combined roles do not apply handles

### ISSUE THREAD

**Issue by bbrtj** [tobyink/p5-sub-handlesvia#6]
This will not work:
```
use v5.36;

package TestRole1 {
	use Moose::Role;

}

package TestRole2 {
	use Moose::Role;
	use Types::Standard qw(ArrayRef);
	use Sub::HandlesVia;

	has 'test' => (
		is => 'ro',
		isa => ArrayRef,
		default => sub { [] },
		handles_via => 'Array',
		handles => {
			all_test => 'all'
		}
	);

}

package TestClass {
	use Moose;

	with qw(
		TestRole1
		TestRole2
	);

	__PACKAGE__->meta->make_immutable;
}

print TestClass->new(test => [1, 2])->all_test;
```

To fix this, either:
- apply roles with `with` individually (wrong)
- `use Sub::HandlesVia` explicitly on the class consuming the roles

From these symptoms, seems like package trait is not applied correctly after applying the role.

Also reproducible in Mouse, but cannot be fixed by adding the import to the package.

**Comment by bbrtj** [comment]
`PackageTrait` is fine, since applying it manually to every class and role also fixes the problem.

**Comment by tobyink** [comment]
Interesting case. I imagine a similar issue exists with this, but haven't actually checked:

```perl
use v5.36;

package TestRole2 {
	use Moose::Role;
	use Types::Standard qw(ArrayRef);
	use Sub::HandlesVia;

	has 'test' => (
		is => 'ro',
		isa => ArrayRef,
		default => sub { [] },
		handles_via => 'Array',
		handles => {
			all_test => 'all'
		}
	);
}

package TestRole3 {
	use Moose::Role;
	with 'TestRole1';
}

package TestClass {
	use Moose;
	with 'TestRole3';
	__PACKAGE__->meta->make_immutable;
}

print TestClass->new(test => [1, 2])->all_test;
```

I'll try to figure out a fix for it this week.

**Comment by tobyink** [comment]
Mouse seems more complicated.

**Comment by bbrtj** [comment]
Wouldn't it be better at this point to just have package trait apply attribute trait to attributes which have handles_via? It was probably not an option before (when Role::Tiny was involved), but now seems doable.

Just a thought, haven't actually checked if the code can be adjusted to maintain the same interface with attribute traits.

**Comment by tobyink** [comment]
Yeah, attribute traits may be the better option.

**Comment by tobyink** [comment]
Though as I recall, that was tricky, as I needed to be able to hook in before the Mo{ou}se::Meta::Attribute constructor was called for some reason.

**Comment by tobyink** [comment]
For now, I think I'll document that role support is only partial for Mouse, and include the test case as a todo.
